// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnovwlakfrjmtvpeluor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZub3Z3bGFrZnJqbXR2cGVsdW9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTQ1NTksImV4cCI6MjA3Mjk5MDU1OX0.XHNB3xTHAndYbyeNDj9nlK6LhI0b1z_7DGsPnsYGXZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});